-- Superstore ETL - Star Schema
-- Run this script against your PostgreSQL database to create the tables.

-- Drop tables in reverse dependency order (fact first, then dimensions)
DROP TABLE IF EXISTS fact_sales;
DROP TABLE IF EXISTS dim_customer;
DROP TABLE IF EXISTS dim_product;
DROP TABLE IF EXISTS dim_location;

-- =============================================================================
-- DIMENSION TABLES
-- =============================================================================

CREATE TABLE dim_customer (
    customer_sk   INTEGER PRIMARY KEY,        -- surrogate key (generated by ETL)
    customer_id   VARCHAR(20) NOT NULL,        -- natural key from source (e.g. "CG-12520")
    customer_name VARCHAR(100) NOT NULL,
    segment       VARCHAR(20) NOT NULL         -- Consumer, Corporate, Home Office
);

CREATE TABLE dim_product (
    product_sk   INTEGER PRIMARY KEY,          -- surrogate key
    product_id   VARCHAR(20) NOT NULL,         -- natural key from source (e.g. "FUR-BO-10001798")
    product_name VARCHAR(300) NOT NULL,
    category     VARCHAR(50) NOT NULL,         -- Furniture, Office Supplies, Technology
    sub_category VARCHAR(50) NOT NULL
);

CREATE TABLE dim_location (
    location_sk  INTEGER PRIMARY KEY,          -- surrogate key
    region       VARCHAR(20) NOT NULL,         -- South, West, Central, East
    country      VARCHAR(50) NOT NULL,
    city         VARCHAR(100) NOT NULL,
    state        VARCHAR(50) NOT NULL,
    postal_code  VARCHAR(10) NOT NULL
);

-- =============================================================================
-- FACT TABLE
-- =============================================================================

CREATE TABLE fact_sales (
    order_id     VARCHAR(20) NOT NULL,
    order_date   DATE NOT NULL,
    ship_date    DATE NOT NULL,
    ship_mode    VARCHAR(20) NOT NULL,          -- Second Class, Standard Class, First Class, Same Day
    sales        NUMERIC(10, 4) NOT NULL,       -- up to 999,999.9999
    customer_sk  INTEGER NOT NULL REFERENCES dim_customer(customer_sk),
    product_sk   INTEGER NOT NULL REFERENCES dim_product(product_sk),
    location_sk  INTEGER NOT NULL REFERENCES dim_location(location_sk)
);

-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE INDEX idx_fact_sales_order_date   ON fact_sales(order_date);
CREATE INDEX idx_fact_sales_customer_sk  ON fact_sales(customer_sk);
CREATE INDEX idx_fact_sales_product_sk   ON fact_sales(product_sk);
CREATE INDEX idx_fact_sales_location_sk  ON fact_sales(location_sk);
